### PR TITLE
#MAN-515 Stratcomm edits to the website

### PR DESCRIPTION
**Pull request by cdoyle-temple**
Update other items as listed in ticket comments

### CODE REVIEW

**Comment by nomadicoder** [comment]
> My Account Shifted Down. Please fix, unless it's fixed elsewhere.
> 
> MAN-515-Shifted-Myaccount

I was unable to reproduce this bug, so I'll mark this request resolved..

**Comment by nomadicoder** [comment]
@cdoyle-temple: Please fix misaligned search button.


MAN-515-Note search button out of alighment

**Comment by cdoyle-temple** [comment]
Updated css for Firefox display of search submit button.

**Comment by cdoyle-temple** [comment]
That's no illusion!!

**Comment by cdoyle-temple** [comment]
Updated position by one pixel

**Pull request merged**
