### PR TITLE
Create Service class

### PR DESCRIPTION
**Pull request by nomadicoder**
Issue #MAN-21

Creates Service model class.

### CODE REVIEW

**Comment by nomadicoder** [comment]
@cdoyle-temple - Would you add admin and views?

**Comment by nomadicoder** [comment]
Assigning User Interface and Administrate portions to @cdoyle-temple

**Comment by bibliotechy** [comment]
Getting an error when trying to save a new Service saying that the group is invalid 
screen shot 2018-09-25 at 8 48 01 pm

even though a group has been selected 
screen shot 2018-09-25 at 8 51 25 pm

**Comment by bibliotechy** [comment]
@nomadicoder Did you see my comment on this?

**Comment by nomadicoder** [comment]
@bibliotechy I ran the spec locally and it passed. I wonder if there's a flaw in the way we're generating related associations. I'm curious if we force a new check to see if it fails. I'd like to see if it's repeatable. Then I can proceed accordingly.

**Comment by nomadicoder** [comment]
@bibliotechy Actually, I've seen this before. It was caused by bad data in the database. I had to drop, remigrate and repopulate my database. I realize this will be a problem if we have production data.

**Comment by bibliotechy** [comment]
Took the steps mentioned and that fixed my issue.

**Pull request merged**
