### PR TITLE
#MAN-220 Update routes for Collections, Services, and Policies

### PR DESCRIPTION
**Pull request by cdoyle-temple**
#MAN-220 Update routes for Collections, Services, and Policies

Remove the index route from Collections, Services, and Policies as the index will be a sidebar on the show page.

***********************************

remove index routes for services, collections, and policies

### CODE REVIEW

**Comment by bibliotechy** [comment]
Not going to merge any PRs that hard code IDs.

**Comment by bibliotechy** [comment]
Didn't intend to close this. Just meant to comment.

**Comment by cdoyle-temple** [comment]
Removed those from this PR. They are still in PR #303 and we can solve the issue there. They don't need to be in this to accomplish what is needed for the issue.

**Comment by cdoyle-temple** [comment]
Removing the hard coding of IDs leaves the entity path (services_path) as undefined since we removed the index page for Services and put the list of all Services on the Show page for each Service, hoping to use one specific Service as the entry point if not ID is passed. Putting the index route back for these will resolve this error but re-introduce another: /services will now present an error to the user since there no longer is an Index view. 

Should we meet with Cynthia since she has spec'd out direct links to the index page for these entities in the site footer?

**Pull request closed without merging**
