### PR TITLE
Remove skylight gem to test app speed

### PR DESCRIPTION
**Pull request by sensei100**

### CODE REVIEW

**Comment by cdoyle-temple** [comment]
@sensei100 Should the Gemfile.lock also be included?

**Review by nomadicoder — APPROVED** [review]

**Review by dkinzer — APPROVED** [review]

**Review by cdoyle-temple — CHANGES_REQUESTED** [review]
@sensei100 Should the Gemfile.lock also be included?

**Comment by sensei100** [comment]
@cdoyle-temple There were no changes to the lock file because we were only using skylight in kubernetes.

**Review by cdoyle-temple — APPROVED** [review]

**Comment by cdoyle-temple** [comment]
Got it

**Pull request merged**
