### PR TITLE
Category Icon Fix

### PR DESCRIPTION
**Pull request by cdoyle-temple**
Add imageable concern to Category model. 
Remove image field from model.

View was not finding image.attachment  before these changes.

### CODE REVIEW

**Comment by bibliotechy** [comment]
@cdoyle-temple Which view? I see them on the [landing pages](https://web.qa.tul-infra.page/research-services). Where should I check this?

**Comment by cdoyle-temple** [comment]
@bibliotechy This was in regard to an issue that the icons were not showing up when a new icon was uploaded for a category. In testing locally, the image.attachment.nil? was coming back true and so skipping the uploaded icon and presenting the default Temple T icon. This fix should allow the image.attachment.nil? to come back false and present the correct icon. You should see the uploaded icons on the About page.

**Comment by bibliotechy** [comment]
@cdoyle-temple But if I go to https://web.qa.tul-infra.page/about right now, I see images.

**Comment by cdoyle-temple** [comment]
So that's unexpected given the conversation this morning with Rachel and Cynthia. One thing this fix does do, though, is make the Category model more like other models that have images by using the imageable concern, which it was not doing.

**Pull request merged**
